name: cardioroad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacotes existentes
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.9.0
  cpf_cnpj_validator: ^2.0.0
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.0.0
  http: ^1.2.1
  url_launcher: ^6.2.5

  # NOVOS PACOTES ADICIONADOS
  fl_chart: ^0.66.2  # Para os gráficos
  intl: ^0.19.0      # Para formatar datas (ex: "15/09")

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/postos_ro.json

