name: cardioroad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacotes do Firebase (para o Back-end)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Pacotes de utilidades e UI
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.9.0
  cpf_cnpj_validator: ^2.0.0
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.0.0
  url_launcher: ^6.2.5
  fl_chart: ^0.66.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Declaração dos assets (arquivos locais)
  assets:
    - assets/postos_ro.json


