// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4uBDyZPwIvfZITuLbxhgMps2tUrMkxIc',
    appId: '1:879338207801:web:9f3804af76afd745ecabe8',
    messagingSenderId: '879338207801',
    projectId: 'cardioroad',
    authDomain: 'cardioroad.firebaseapp.com',
    storageBucket: 'cardioroad.firebasestorage.app',
    measurementId: 'G-XSDV6L0Q3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVCiUXauiylSkJf_AiFodX2MZlMO313sg',
    appId: '1:879338207801:android:c58a835634c1eb8decabe8',
    messagingSenderId: '879338207801',
    projectId: 'cardioroad',
    storageBucket: 'cardioroad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmSk5pihZI8QSA6ALRFqTJaaZsJmNCjsU',
    appId: '1:879338207801:ios:bcc374deeba26781ecabe8',
    messagingSenderId: '879338207801',
    projectId: 'cardioroad',
    storageBucket: 'cardioroad.firebasestorage.app',
    iosBundleId: 'com.example.cardioroad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmSk5pihZI8QSA6ALRFqTJaaZsJmNCjsU',
    appId: '1:879338207801:ios:bcc374deeba26781ecabe8',
    messagingSenderId: '879338207801',
    projectId: 'cardioroad',
    storageBucket: 'cardioroad.firebasestorage.app',
    iosBundleId: 'com.example.cardioroad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4uBDyZPwIvfZITuLbxhgMps2tUrMkxIc',
    appId: '1:879338207801:web:3cbebdcd1fcf81f3ecabe8',
    messagingSenderId: '879338207801',
    projectId: 'cardioroad',
    authDomain: 'cardioroad.firebaseapp.com',
    storageBucket: 'cardioroad.firebasestorage.app',
    measurementId: 'G-6ZRKGGDVX1',
  );
}
